version: '3.9'

services:
  payara:
    container_name: payara
    build: .
    ports:
      - "9680:8080"
      - "9681:8181" # web https
      - "9648:4848" # admin
      - "9690:9009" # debug
    volumes:
      - ${PWD}/target/trippidy-1.0.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/trippidy-1.0.0-SNAPSHOT.war
    depends_on:
      - db
      - liquibase

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - trippidy-db-volume:/var/lib/postgresql/data
    ports:
      - "9654:5432"

  liquibase:
    image: liquibase/liquibase:4.13.0
    container_name: liquibase
    depends_on:
      - db
    volumes:
      - ${PWD}/src/main/resources/changelog/:/liquibase/changelog/
    command: --defaults-file=/liquibase/changelog/local.properties update

volumes:
  trippidy-db-volume: