version: '3.3'

services:

  flutter-web-app:
    container_name: flutter-web-app
    build:
      context: https://github.com/koty10/trippidy.git#master
    depends_on:
      - nginx
    networks:
      - trippidy_network

  trippidy-payara-direct:
    #container_name: trippidy-payara
    build: .
    ports:
       - "1234:8080"
    #   - "9681:8181" # web https
    #   - "9648:4848" # admin
    #  - "9690:9009" # debug
    #expose:
      #- "8080"
      #- "8181"
      #- "4848"
      #- "9009"
    volumes:
      - ./target/trippidy-1.0.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/trippidy-1.0.0-SNAPSHOT.war
    depends_on:
      - db
      - liquibase
    networks:
      - trippidy_network

  trippidy-payara:
    #container_name: trippidy-payara
    build: .
    ports:
    #   - "9680:8080"
    #   - "9681:8181" # web https
    #   - "9648:4848" # admin
      - "9690:9009" # debug
    expose:
      - "8080"
      - "8181"
      - "4848"
    #  - "9009"
    volumes:
      - ./target/trippidy-1.0.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/trippidy-1.0.0-SNAPSHOT.war
    depends_on:
      - db
      - liquibase
    networks:
      - trippidy_network

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    #volumes:
    #  - trippidy-db-volume:/var/lib/postgresql/data
    ports:
      - "9654:5432"
    networks:
      - trippidy_network

  liquibase:
    image: liquibase/liquibase:4.13.0
    container_name: liquibase
    depends_on:
      - db
    volumes:
      - ./src/main/resources/changelog/:/liquibase/changelog/
    command: --defaults-file=/liquibase/changelog/local.properties update
    networks:
      - trippidy_network

  nginx:
    image: nginx:alpine3.18
    container_name: nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "9680:443"
    depends_on:
      - trippidy-payara
      - jenkins
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - trippidy_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - trippidy_network
      
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    expose:
      - "50000"
      - "8080"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - trippidy_network

volumes:
  trippidy-db-volume:
  jenkins_home:

networks:
  trippidy_network:
    driver: bridge
