version: '3.9'

services:
  payara:
    image: payara/micro:6.2023.2
    ports:
      - "8080:8080"
    volumes:
      - ./target/trippidy-v1.war:/opt/payara/deployments/trippidy-v1.war
      - ./payara-micro:/opt/payara/micro
      - ./logs:/opt/payara/appserver/glassfish/domains/production/logs
    environment:
      - DEPLOY_PROPS=jdbcUrl=jdbc:postgresql://db/trippidydb,driverClass=org.postgresql.Driver,user=admin,password=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=trippidydb
    volumes:
      - trippidy-db-volume:/var/lib/postgresql/data
    ports:
      - "8760:5432"

volumes:
  trippidy-db-volume: