version: '3.9'

services:
  payara:
    container_name: payara
    build: .
    ports:
      - "8080:8080"
      - "8181:8181" # web https
      - "4848:4848" # admin
      - "9009:9009" # debug
    volumes:
      - ./target/trippidy-v1.war:/opt/payara/deployments/trippidy-v1.war
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - trippidy-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase:4.13.0
    container_name: liquibase
    depends_on:
      - db
    volumes:
      - ./src/main/resources/changelog/:/liquibase/changelog/
    command: --defaults-file=/liquibase/changelog/local.properties update

volumes:
  trippidy-db-volume: